### ISSUE TITLE
Get rid of LibLog

### ISSUE THREAD

**Issue by kudlosh** [newtontechnologies/beey-dotnet-client#1]
For some reason Channel-mixer cannot be built correctly because of LibLog. Replace LibLog with Microsoft.Extensions.Logging with minimum effort.

**Comment by Ttxman** [comment]
Ja bych spis namiril na ciste zakladni Serilog.
Liblog pouziva staticky loggery a ten zpusob propagace pomoci construktor injection podle me nemusi byt "minimum effort".
Plus serilog se docela dobre napojuje na ten MS logging pokud, aplikace bezi v jakymkoliv generic hostu

**Comment by kudlosh** [comment]
jo, udělal jsem to jinak právě
